spring:
    r2dbc:
        url: r2dbc:pool:mysql://localhost:3306/webflux_practice?useSSL=true
        username: root
        password: password
    docker:
        compose:
            file: ./docker/docker-compose.yml
logging:
    level:
        org.springframework.r2dbc.core: DEBUG
springdoc:
    swagger-ui:
        path: /swagger-ui.html

